Repository ko9612/ZikTalk, pull requests merged in 2025-05, with the labels that each got.

#2 Title: [#1] Read me 내용추가
  README.md
Labels: 📓Docs, ⚙Setting

#3 test: 테스트(#1)
  README.md
Labels: ✅Test

#4 test: discord webhook test
  README.md
  zik_cilent/.gitignore
  zik_cilent/eslint.config.js
  zik_cilent/index.html
  zik_cilent/package-lock.json
  zik_cilent/package.json
  zik_cilent/public/vite.svg
  zik_cilent/src/App.css
  zik_cilent/src/App.jsx
  zik_cilent/src/assets/react.svg
  zik_cilent/src/index.css
  zik_cilent/src/main.jsx
  zik_cilent/vite.config.js
Labels: ✅Test

#6 [#5] feat: 공통 컴포넌트(Top button, Chatbot button 구현, Layout 임의로 구현)
  client/package-lock.json
  client/package.json
  client/src/components/common/ChatbotBotton.jsx
  client/src/components/common/Layout.jsx
  client/src/components/common/TopButton.jsx
  client/src/components/common/chatbot/ChatContainer.jsx
  client/src/pages/Landing/index.jsx
  client/src/store/useVisibilityStore.jsx
  client/src/styles/global.css
Labels: 🎨CSS, 🌟Feature

#7 [#5] feat: 공통 모달 구현
  client/jsconfig.json
  client/src/components/chatbot/ChatContainer.jsx
  client/src/components/common/ChatbotBotton.jsx
  client/src/components/common/LoadingIcon.jsx
  client/src/components/common/Modal.jsx
  client/src/components/common/Modal/CareerSelectModal.jsx
  client/src/components/common/Modal/CommonModal.jsx
  client/src/components/common/Modal/Modal.jsx
  client/src/components/common/TopButton.jsx
  client/src/components/common/chatbot/ChatContainer.jsx
  client/src/data/carrerData.js
  client/src/pages/Interview/_components/AnalysisCompleteIcon.jsx
  client/src/pages/Interview/_components/AnalysisStateModal.jsx
  client/src/pages/Interview/_components/example.jsx
  client/src/pages/Test.jsx
  client/src/router/index.jsx
  client/src/styles/global.css
  client/vite.config.js
Labels: 🎨CSS, 🌟Feature

#8 [#5] style: 모달 반응형 적용(#5)
  client/src/components/common/Modal/CareerSelectModal.jsx
  client/src/components/common/Modal/Modal.jsx
  client/src/pages/Interview/_components/AnalysisStateModal.jsx
Labels: 🎨CSS

#12 [#5] feat: 공통컴포넌트(헤더, 푸터, 인터뷰탭, 마이페이지탭) (#5)
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/InterviewTap.jsx
  client/src/components/common/MyPageTap.jsx
Labels: 🎨CSS

#15 [#14] feat: landing KeyPointSection
  client/src/assets/images/difficulty-level.svg
  client/src/assets/images/feedback.svg
  client/src/assets/images/job-question.svg
  client/src/pages/Landing/_components/KeyPointSection.jsx
Labels: 🎨CSS

#16 [#5] fix: 헤더, 푸터(이미지 추가), 인터뷰탭, 마이페이지탭 세부 사항 수정, Layout 헤더 푸터 컴포넌트로 설정 (#5)
  client/src/assets/images/github.svg
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/InterviewTap.jsx
  client/src/components/common/Layout.jsx
  client/src/components/common/MyPageTap.jsx
Labels: 🤬BugFix, 🎨CSS

#22 [#5] fix: 버튼 호버 수정(배경만 적용되게)
  client/src/components/common/Button.jsx
Labels: 🎨CSS

#24 [#5] landing-KeyPointSection반응형적용
  client/src/pages/Landing/_components/KeyPointSection.jsx
Labels: 🎨CSS

#25 [#14] feat: 랜딩 Feature Section 구현
  client/package-lock.json
  client/package.json
  client/src/assets/images/analysisPage_example.svg
  client/src/assets/images/landing_icon/job_accounter.svg
  client/src/assets/images/landing_icon/job_analyzer.png
  client/src/assets/images/landing_icon/job_gameDeveloper.png
  client/src/assets/images/landing_icon/job_marketer.svg
  client/src/assets/images/landing_icon/job_nurse.png
  client/src/assets/images/landing_icon/job_productManager.png
  client/src/assets/images/landing_icon/job_security.png
  client/src/assets/images/landing_icon/job_servicePlanner.png
  client/src/assets/images/landing_icon/job_teacher.svg
  client/src/assets/images/landing_icon/job_videoEditor.png
  client/src/assets/images/landing_icon/job_webDesigner.svg
  client/src/assets/images/landing_icon/job_webDeveloper.svg
  client/src/components/common/FaqItem.jsx
  client/src/components/common/FilterDropdown.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/Modal/CareerSelectModal.jsx
  client/src/components/common/Modal/CommonModal.jsx
  client/src/data/landingData.jsx
  client/src/data/testData.js
  client/src/pages/Interview/_components/AnalysisStateModal.jsx
  client/src/pages/Landing/_components/FeatureSection.jsx
  client/src/pages/Landing/_components/card/JobCard.jsx
  client/src/pages/Test.jsx
Labels: 🎨CSS, 🌟Feature

#28 [#5] style: 버튼 호버 색상 변경
  client/src/components/common/Button.jsx
Labels: 🎨CSS

#29 [#14] landing KeyPointSection 반응형 수정
  client/src/assets/images/difficulty-level.svg
  client/src/assets/images/feedback.svg
  client/src/assets/images/job-question.svg
  client/src/pages/Landing/_components/KeyPointSection.jsx
Labels: 🎨CSS

#30 fix: 공통 컴포넌트 및 메인 컴포넌트 레이아웃 수정 (#14)
  client/src/components/common/FaqItem.jsx
  client/src/components/common/FilterDropdown.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/InterviewTab.jsx
  client/src/components/common/Layout.jsx
  client/src/components/common/Modal/CareerSelectModal.jsx
  client/src/components/common/Modal/CommonModal.jsx
  client/src/components/common/Modal/Modal.jsx
  client/src/components/common/MyPageTab.jsx
  client/src/components/common/Pagination.jsx
  client/src/pages/Interview/_components/AnalysisStateModal.jsx
  client/src/pages/Landing/_components/BottomSection.jsx
  client/src/pages/Landing/_components/FeatureSection.jsx
  client/src/pages/Landing/_components/GuideSection.jsx
  client/src/pages/Landing/_components/HeroSection.jsx
  client/src/pages/Landing/index.jsx
  client/src/pages/Test.jsx
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#33 [#5] style:framer-motion 적용
  client/src/pages/Landing/_components/KeyPointSection.jsx
Labels: 🎨CSS

#34 [#5] style: duration 수정
  client/src/components/common/Button.jsx
Labels: 🎨CSS

#36 [#35] feat: interview 페이지 관련 컴포넌트들 생성, interview 페이지 레이아웃 추가
  client/src/components/common/Header.jsx
  client/src/components/common/InterviewTab.jsx
  client/src/pages/Interview/InterViewLayout.jsx
  client/src/pages/Interview/_components/interview/AnalysisCompleteIcon.jsx
  client/src/pages/Interview/_components/interview/AnalysisStateModal.jsx
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/interview/QuestionBox.jsx
  client/src/pages/Interview/_components/interview/Timer.jsx
  client/src/pages/Interview/_components/setting/example.jsx
  client/src/pages/Interview/index.jsx
  client/src/pages/Landing/_components/BottomSection.jsx
  client/src/pages/Landing/_components/FeatureSection.jsx
  client/src/pages/Landing/_components/HeroSection.jsx
  client/src/pages/Landing/_components/KeyPointSection.jsx
  client/src/pages/Test.jsx
  client/src/router/index.jsx
Labels: 🎨CSS, 🌟Feature

#38 [#14] fix: 에러 수정
  client/src/pages/Landing/_components/KeyPointSection.jsx
Labels: 🤬BugFix

#39 [#35] feat: interview tab state 추가
  client/src/components/common/ChatbotBotton.jsx
  client/src/components/common/InterviewTab.jsx
  client/src/components/common/TopButton.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/store/store.jsx
  client/src/store/useVisibilityStore.jsx
Labels: 🎨CSS, 🌟Feature

#41 fix: interview state 추가 (#35)
  client/src/components/common/ChatbotBotton.jsx
  client/src/components/common/InterviewTab.jsx
  client/src/components/common/TopButton.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/store/store.jsx
  client/src/store/useVisibilityStore.jsx
Labels: 🌟Feature

#43 [#5] change input text color
  client/src/components/common/Input.jsx
Labels: 🎨CSS

#45 [#44] 로그인 퍼블리싱
  client/src/assets/images/google.svg
  client/src/assets/images/kakao.svg
  client/src/pages/Signin/_components/SigninForm.jsx
  client/src/pages/Signin/index.jsx
  client/src/router/index.jsx
Labels: 🎨CSS

#52 fix: 인터뷰 페이지 레이아웃 수정 (#35)
  client/src/components/common/Modal/CommonModal.jsx
  client/src/hooks/useBlocker.js
  client/src/pages/Interview/InterViewLayout.jsx
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/interview/Timer.jsx
  client/src/store/store.jsx
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#55 [#54] 회원가입 퍼블리싱
  client/src/pages/Signup/_components/SignupForm.jsx
  client/src/pages/Signup/index.jsx
Labels: 🎨CSS

#59 style: DeviceSetup & screensize Guide 컴포넌트 레이아웃 수정
  client/src/components/common/ScreenSizeGuide.jsx
  client/src/pages/Interview/_components/setting/DeviceSetup.jsx
Labels: 🎨CSS

#60 [#49] fix: interview setting 페이지 css 수정
  client/src/pages/Interview/_components/setting/DiffSetup.jsx
  client/src/pages/Interview/_components/setting/DragProgressBar.jsx
  client/src/pages/Interview/_components/setting/PreCheckStep.jsx
  client/src/pages/Interview/_components/setting/RoleSetup.jsx
Labels: 🎨CSS

#63 fix: graph 부드럽게 움직이도록 변경 (#35)
  client/src/hooks/useSmoothvalue.js
  client/src/pages/Interview/_components/interview/Timer.jsx
Labels: 🤬BugFix, 🌟Feature

#64 fix: timer settime 수정 (#35)
  client/src/pages/Interview/_components/interview/Timer.jsx
Labels: 🤬BugFix

#67 [#27] feat:sohyun interview result
  client/src/components/common/Graph.jsx
  client/src/pages/Interview-result/_components/BoxStyle.jsx
  client/src/pages/Interview-result/_components/Comprehensive.jsx
  client/src/pages/Interview-result/_components/GraphResult.jsx
  client/src/pages/Interview-result/_components/Question.jsx
  client/src/pages/Interview-result/index.jsx
Labels: 🎨CSS

#68 [#66] 사용 안 하는 파일 삭제
  client/src/pages/Interview-result/_components/InterviewVideo.jsx
  client/src/pages/Interview-result/_components/Question.jsx
  client/src/pages/Interview-result/index.jsx
Labels: 🎨CSS

#71 [#35] feat: myPage Layout, 여러 컴포넌트 문법 에러 수정 + 로딩 및 에러 페이지 적용
  client/src/App.jsx
  client/src/components/common/FaqItem.jsx
  client/src/components/common/FilterDropdown.jsx
  client/src/components/common/Modal/Modal.jsx
  client/src/components/common/NotFoundPage.jsx
  client/src/data/faqData.js
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Signin/_components/SigninForm.jsx
  client/src/pages/Signup/_components/SignupForm.jsx
  client/src/pages/myPage/_components/bookmark/EmptyBookmarkList.jsx
  client/src/pages/myPage/_components/bookmark/QuestionBookmarkList.jsx
  client/src/pages/myPage/_components/bookmark/settings/components.jsx
  client/src/pages/myPage/_components/common/ResultCard.jsx
  client/src/pages/myPage/_components/common/TableHeader.jsx
  client/src/pages/myPage/_components/info/MyInfo.jsx
  client/src/pages/myPage/_components/question/EmptyQuestionList.jsx
  client/src/pages/myPage/_components/question/QuestionList.jsx
  client/src/pages/myPage/_components/question/settings/components.jsx
  client/src/pages/myPage/index.jsx
  client/src/router/index.jsx
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#74 [#65] Backend 세팅 및 연동
  client/src/api/testApi.js
  client/src/pages/Test.jsx
  server/.gitignore
  server/package.json
  server/prisma/schema.prisma
  server/src/controllers/interviewController.js
  server/src/index.js
  server/src/middleware/authMiddleware.js
  server/src/routes/interview.route.js
  server/src/routes/root.route.js
  server/src/services/interviewService.js
  server/src/utils/prisma.js
Labels: Backend, ⚙Setting, ✅Test

#75 [#49] 인터뷰 세팅 페이지 수정
  client/src/pages/Interview/_components/setting/DiffSetup.jsx
  client/src/pages/Interview/_components/setting/DragProgressBar.jsx
  client/src/pages/Interview/_components/setting/PreCheckStep.jsx
  client/src/pages/Interview/index.jsx
  client/src/store/interviewSetupStore.jsx
Labels: 🎨CSS

#78 [#49] 인터뷰 세팅 화면 zustand store 변수들 정리, 인터뷰 섹션에 변수 추가
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/setting/DiffSetup.jsx
  client/src/pages/Interview/_components/setting/DragProgressBar.jsx
  client/src/pages/Interview/_components/setting/PreCheckStep.jsx
  client/src/pages/Interview/_components/setting/RoleSetup.jsx
  client/src/pages/Interview/index.jsx
  client/src/store/interviewSetupStore.jsx
Labels: 🤬BugFix, 🏭Refactor

#80 [#54] feat: 회원가입 유효성 검사
  client/package-lock.json
  client/package.json
  client/src/pages/Signup/_components/SignupForm.jsx
Labels: 🌟Feature

#81 feat: openai 연동 + daglo 연동(작업 중) (#66)
  client/package-lock.json
  client/src/api/interviewApi.js
  client/src/main.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/interview/QuestionBox.jsx
  client/src/pages/Interview/_components/interview/Timer.jsx
  client/src/store/store.jsx
  server/package.json
  server/src/controllers/interview.controller.js
  server/src/controllers/interviewController.js
  server/src/index.js
  server/src/routes/interview.route.js
  server/src/routes/root.route.js
  server/src/services/interviewService.js
Labels: 🚀API, Backend, 🌟Feature

#83 [#82] fix: 인터뷰 CRUD 관련
  server/src/controllers/interview.controller.js
  server/src/routes/interview.route.js
  server/src/services/interviewDBService.js
Labels: Backend

#84 fix: open ai 요청 prompt 수정 및 기능 수정 (#35)
  client/src/api/interviewApi.js
  client/src/api/testApi.js
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/interview/QuestionBox.jsx
  client/src/pages/Interview/_components/interview/Timer.jsx
  client/src/pages/Interview/index.jsx
  client/src/store/store.jsx
Labels: 🚀API, Backend, 🌟Feature

#87 [#82] feat: 녹화기능 / 인터뷰, 질문목록 저장, 조회 기능
  client/package-lock.json
  client/package.json
  client/src/pages/Interview/_components/interview/InterviewList.jsx
  client/src/pages/Interview/_components/interview/RecordSection.jsx
  client/src/pages/Interview/_components/setting/DeviceSetup.jsx
  client/src/pages/Interview/_components/setting/MediaDeviceSelector.jsx
  client/src/pages/Interview/index.jsx
  client/src/pages/Test.jsx
  client/src/store/mediaDeviceStore.jsx
  server/.gitignore
  server/package.json
  server/src/controllers/recordController.js
  server/src/routes/record.route.js
  server/src/routes/root.route.js
  server/src/services/interviewDBService.js
Labels: Backend

#90 feat: interview 기능 수정 (#35)
  client/src/pages/Interview/_components/interview/AnalysisStateModal.jsx
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/interview/Timer.jsx
  server/src/controllers/interview.controller.js
  server/src/index.js
  server/src/services/interviewService.js
Labels: 🌟Feature

#92 Feat/hana interview
  client/src/api/interviewApi.js
  client/src/hooks/useRecord.js
  client/src/pages/Interview/_components/interview/AnalysisStateModal.jsx
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/interview/QuestionBox.jsx
  client/src/pages/Interview/_components/interview/Timer.jsx
  client/src/store/store.jsx
  server/src/controllers/interview.controller.js
  server/src/routes/interview.route.js
  server/src/services/interviewService.js
Labels: 🚀API, Backend, 🌟Feature

#93 [#54] signup API 연동, 회원가입완료 모달
  client/src/api/signApi.js
  client/src/hooks/useAuth.js
  client/src/pages/Signup/_components/SignupForm.jsx
  server/src/controllers/auth.controller.js
  server/src/routes/auth.route.js
  server/src/routes/root.route.js
  server/src/services/authService.js
Labels: 🚀API

#94 [#44] signin 유효성검사, API 연동, JWT
  client/src/components/common/Header.jsx
  client/src/main.jsx
  client/src/pages/Signin/_components/SigninForm.jsx
Labels: 🚀API, Backend

#95 feat: sst 기능 수정(다글로->라이브러리) (#35)
  client/package-lock.json
  client/package.json
  client/src/hooks/useRecord.js
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/index.jsx
  client/src/pages/Test.jsx
  server/src/index.js
Labels: 🤬BugFix, 🌟Feature

#96 [#44] 이메일 기억하기 추가
  client/src/pages/Signin/_components/SigninForm.jsx
Labels: 🌟Feature

#97 [#35] feat: ai 피드백 요청 기능 추가 (#35)
  client/src/api/interviewApi.js
  client/src/pages/Interview/_components/interview/AnalysisStateModal.jsx
  server/src/controllers/interview.controller.js
  server/src/routes/interview.route.js
  server/src/services/interviewDBService.js
  server/src/services/interviewService.js
Labels: 🚀API, Backend, 🌟Feature

#99 [#35] 면접 분석 결과+면접 데이터 전달 구현, 인터뷰 페이지 비로그인 접근 방지
  client/src/api/interviewApi.js
  client/src/pages/Interview/_components/interview/AnalysisStateModal.jsx
  client/src/pages/Interview/index.jsx
  server/src/services/interviewDBService.js
  server/src/services/interviewService.js
Labels: 🚀API, Backend, 🌟Feature

#100 [#54] 인증하기 타이머 추가, 코드 정리
  client/src/pages/Signup/_components/SignupForm.jsx
Labels: 🌟Feature, 🏭Refactor

#101 [#54] 이메일 인증 구현 (nodemailer)
  client/src/api/signApi.js
  client/src/pages/Signup/_components/SignupForm.jsx
  server/package.json
  server/src/assets/images/logo.webp
  server/src/controllers/auth.controller.js
  server/src/middleware/auth.middleware.js
  server/src/routes/auth.route.js
  server/src/services/authService.js
Labels: 🌟Feature

#102 fix: 음성인식 안정화 + 타이머 안 돌아가는 문제 해결 (#35)
  client/src/pages/Interview/_components/interview/Answer.jsx
  client/src/pages/Interview/_components/interview/InterviewSection.jsx
  client/src/pages/Interview/_components/interview/Timer.jsx
Labels: 🤬BugFix, 🌟Feature

#103 [#44] accesstoken, refreshtoken, loginStore, 접근제어, 로그아웃, axiosInstance
  client/src/api/axiosInstance.js
  client/src/api/signApi.js
  client/src/components/common/Header.jsx
  client/src/components/common/ProtectedRoute.jsx
  client/src/hooks/useAuth.js
  client/src/pages/Signin/_components/SigninForm.jsx
  client/src/router/index.jsx
  client/src/store/loginStore.jsx
  server/package.json
  server/src/controllers/auth.controller.js
  server/src/index.js
  server/src/middleware/auth.middleware.js
  server/src/routes/auth.route.js
  server/src/services/authService.js
Labels: Backend, 🌟Feature

#104 [#56] 분석 결과 페이지
  client/src/pages/Interview-result/index.jsx
Labels: 🌟Feature

#105 [#44] accessToken 헤더에 저장, refresh 토큰
  client/src/api/axiosInstance.js
  client/src/api/signApi.js
  client/src/hooks/useAuth.js
  server/src/controllers/auth.controller.js
  server/src/middleware/auth.middleware.js
  server/src/routes/auth.route.js
Labels: 🚀API

#106 [#82] supabase 저장소
  client/package-lock.json
  client/package.json
  client/src/pages/Interview/_components/setting/VideoPlayer.jsx
  client/src/utils/supabaseClient.js
  server/package.json
  server/src/controllers/recordController.js
  server/src/routes/record.route.js
  server/src/utils/supabaseClient.js
Labels: Backend

#109 [#49] 인터뷰 세팅 페이지 벗어날때 경고창. header, interviewTab 링크 수정/추가 (#49)
  client/src/components/common/Header.jsx
  client/src/components/common/InterviewTab.jsx
  client/src/hooks/useNavigationBlocker.js
  client/src/pages/Interview/index.jsx
Labels: 🌟Feature

#111 [#66] 분석 결과 페이지 질문 북마크 완료
  client/src/api/signApi.js
  client/src/pages/Interview-result/index.jsx
  server/src/controllers/question.controller.js
  server/src/routes/question.route.js
Labels: 🚀API

#113 [#82] feat: 유저 컴포넌트 제작
  client/src/api/axiosInstance.js
  client/src/api/interviewApi.js
  client/src/components/common/Header.jsx
  client/src/pages/Interview/_components/interview/AnalysisStateModal.jsx
  client/src/pages/Interview/_components/setting/DiffSetup.jsx
  client/src/pages/Interview/index.jsx
  client/src/store/interviewSetupStore.jsx
  client/src/store/loginStore.jsx
  server/package.json
  server/src/controllers/interview.controller.js
  server/src/routes/interview.route.js
  server/src/services/interviewDBService.js
  server/src/services/interviewService.js
Labels: 🚀API, Backend, 🌟Feature

#115 [#65] fix: PrismaClient 커넥션풀 문제 해결중 (#65)
  server/src/controllers/interview.controller.js
  server/src/controllers/mypage.controller.js
  server/src/controllers/question.controller.js
  server/src/middleware/auth.middleware.js
  server/src/services/authService.js
  server/src/services/interviewDBService.js
  server/src/services/question.service.js
  server/src/test-update-questions.js
  server/src/utils/prisma.js
  server/test-update.js
Labels: Backend, 🤬BugFix

#117 [#116] token 재발급, 로그인 연장
  client/src/App.jsx
  client/src/api/axiosInstance.js
  client/src/api/signApi.js
  client/src/pages/Signin/_components/SigninForm.jsx
  client/src/store/loginStore.jsx
  server/src/controllers/auth.controller.js
  server/src/routes/auth.route.js
  server/src/services/authService.js
Labels: 🚀API, Backend, 🌟Feature

#129 [#127] 카카오 로그인 구현
  client/src/pages/KakaoCallback/Index.jsx
  client/src/pages/KakaoCallback/_components/KakaoCallback.jsx
  client/src/pages/OauthSignup/Index.jsx
  client/src/pages/OauthSignup/_components/OauthSignup.jsx
  client/src/pages/Signin/_components/SigninForm.jsx
  client/src/pages/Signup/_components/SignupForm.jsx
  client/src/router/index.jsx
  client/src/store/loginStore.jsx
  server/package.json
  server/src/controllers/auth.controller.js
  server/src/routes/auth.route.js
  server/src/services/authService.js
Labels: 🚀API, Backend, 🌟Feature

#131 [#127] 카카오 로그아웃
  client/src/hooks/useAuth.js
  client/src/pages/Signin/_components/SigninForm.jsx
Labels: 🌟Feature

#135 feat: 카카오 회원탈퇴 구현 중+ 탈퇴,수정 완료 모달 수정
  client/src/components/common/Header.jsx
  client/src/components/common/Modal/CommonModal.jsx
  client/src/hooks/useAuth.js
  client/src/pages/myPage/_components/info/MyInfo.jsx
Labels: 🌟Feature

#136 kakaoToken 저장, provider별 로그인 재구현, 비밀번호 재설정 로컬만 가능하게 수정
  client/src/pages/KakaoCallback/_components/KakaoCallback.jsx
  client/src/pages/OauthSignup/_components/OauthSignup.jsx
  server/prisma/migrations/20250527135232_add_kakao_token_to_user/migration.sql
  server/prisma/schema.prisma
  server/src/middleware/auth.middleware.js
  server/src/services/authService.js
Labels: 🌟Feature

#137 Feat/hana delete user
  client/src/hooks/useAuth.js
  client/src/pages/Signin/_components/ResetPassword.jsx
  client/src/pages/myPage/_components/info/MyInfo.jsx
Labels: 🤬BugFix, 🌟Feature

#139 feat: 회원탈퇴 확인 모달 보이게, 로그아웃 조건 처리 완료
  client/src/hooks/useAuth.js
  client/src/pages/KakaoCallback/_components/KakaoCallback.jsx
  client/src/pages/myPage/_components/info/MyInfo.jsx
  client/src/store/loginStore.jsx
Labels: 🌟Feature

#140 [#127] kakao 계정 연동
  client/src/api/signApi.js
  client/src/pages/KakaoCallback/_components/KakaoCallback.jsx
  server/src/controllers/auth.controller.js
  server/src/routes/auth.route.js
  server/src/services/authService.js
Labels: 🌟Feature
